// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoNoe4Y625eMDr0JD3zEgqqVZ8ZAHUB3c',
    appId: '1:750499581525:web:d044b665820e0875d48edc',
    messagingSenderId: '750499581525',
    projectId: 'iyad-f4053',
    authDomain: 'iyad-f4053.firebaseapp.com',
    storageBucket: 'iyad-f4053.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNKkBEzv28fQV31nyK98vELw2v68XUYc',
    appId: '1:750499581525:android:d9afef47100f397ed48edc',
    messagingSenderId: '750499581525',
    projectId: 'iyad-f4053',
    storageBucket: 'iyad-f4053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDULNiynu-tFJEgPU4bx2rDg2fwRp4zo8Q',
    appId: '1:750499581525:ios:a6cb001301e1656ad48edc',
    messagingSenderId: '750499581525',
    projectId: 'iyad-f4053',
    storageBucket: 'iyad-f4053.appspot.com',
    iosBundleId: 'com.example.iyadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDULNiynu-tFJEgPU4bx2rDg2fwRp4zo8Q',
    appId: '1:750499581525:ios:a6cb001301e1656ad48edc',
    messagingSenderId: '750499581525',
    projectId: 'iyad-f4053',
    storageBucket: 'iyad-f4053.appspot.com',
    iosBundleId: 'com.example.iyadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoNoe4Y625eMDr0JD3zEgqqVZ8ZAHUB3c',
    appId: '1:750499581525:web:977aba9ad555f9a4d48edc',
    messagingSenderId: '750499581525',
    projectId: 'iyad-f4053',
    authDomain: 'iyad-f4053.firebaseapp.com',
    storageBucket: 'iyad-f4053.appspot.com',
  );
}
